<script setup lang="ts">
import VMountain from '../components/VMountain.vue';
</script>

<template>
  <div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div>
  <VMountain/>
  <div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div><div>AAAAAAAAAAAAAAAA</div>
</template>
